### ISSUE TITLE
你好，请教一下posenet提出来的position的x坐标为什么这里要乘1.4

### ISSUE THREAD

**Issue by GuaiYiHu** [haruhiii/wechat-posenet#1]
https://github.com/vrilc/wechat-posenet/blob/a76980e8bf19463533d6c732745f67ec3196069c/pages/posenet/index.js#L106

**Comment by GuaiYiHu** [comment]
理论上这个值是要拿相机显示大小和输入大小来的，这个1.4是凑巧的吗

**Comment by haruhiii** [comment]
@GuaiYiHu 随便输入几个数...视觉上1.4比较匹配...
